language: java
jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install: chmod +x ./gradlew
script: ./gradlew check

jobs:
  include:
    - stage: deploy
      jdk: openjdk11
      before_script: chmod +x ./javadoc-deploy.sh
      script: ./javadoc-deploy.sh
      if: tag IS present
    - stage: deploy
      jdk: openjdk8
      install: skip
      script: ./gradlew bintrayUpload -x test
      if: tag IS present